name: 'Stock #4: Content Display'
description: 'Configures display of stock content types. This can be removed after installation.'
type: module
core_version_requirement: ^9
dependencies:
  - fp_site_config_fields
package: 'FivePaths Stocksite Configuration'
