name: 'Stock #2: Content Field Storage'
description: 'Installs and configures field storage on stock content types. This can be removed after installation.'
type: module
core_version_requirement: ^9
dependencies:
  - viewsreference
  - fp_site_config_content_types
package: 'FivePaths Stocksite Configuration'
